### ISSUE TITLE
Battery status endpoint always return 500 error

### ISSUE THREAD

**Issue by devsheder** [hacf-fr/renault-api#1103]
Hi,
I try to call `battery-status` API endpoint and it always return a 500 errors with this payload :
```json
{
  "type": "TECHNICAL",
  "messages": [
    {
      "code": "err.tech.wired.kamereon-proxy",
      "message": "Failed to forward request to remote service."
    }
  ],
  "errors": [
    {
      "errorCode": "err.tech.wired.kamereon-proxy",
      "errorMessage": "Failed to forward request to remote service."
    }
  ],
  "error_reference": "TECHNICAL"
}
```
I have tried those two URLs :
- https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/${accountId}/kamereon/kcm/v2/vehicles/${vin}/battery-status?country=FR
- https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/${accountId}/kamereon/kca/car-adapter/v2/cars/${vin}/battery-status?country=FR

My params are good because I can find my vehicules through `/commerce/v1/accounts/${accountId}/vehicles?country=FR` endpoint

Thanks a lot !

**Comment by epenet** [comment]
This can happen when the Renault servers are mis-behaving, or if the Renault contract has expired.
- do you get valid values on the Phone App?
- do other endpoints work correctly?

Please ensure that you tell us which type of vehicle is causing the issue

**Comment by samwatling** [comment]
This also happens to me. 500 on every battery end point request. I also have no battery data in the Renault App although other connected services (remote pre conditioning etc) work.

Renault Zoe ZE40

**Comment by samwatling** [comment]
This was 'fixed' by a support call to Renault. There was something wrong with my account (I asked what and they didn't have the details). So not a renault-api issue.
