### ISSUE TITLE
vehicle.get_cockpit() returns {"message": "you should not be there but well done for the effort"}

### ISSUE THREAD

**Issue by eltoro0815** [hacf-fr/renault-api#1135]
`cockpit_infos = await vehicle.get_cockpit()`

By enabling DEBUG output I got this:

DEBUG:renault_api.kamereon:Received Kamereon response 200 on GET to https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/{account_id}/kamereon/kca/car-adapter/v2/cars/{vin}/cockpit?country=DE: {"message": "you should not be there but well done for the effort"}

FYI: I replaced the account_id and vin in the debug output ;)

The problem did occur since today. The method get_cockpit() worked as expected for some weeks.
I verified the problem on several devices.

Other requests work as expected, e.g.:

`battery_status = await vehicle.get_battery_status()`

**Comment by eltoro0815** [comment]
I did some research:

A) The "My Dacia" Androip app uses another Endpoint to get the cockpit:

[https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/{account_id}/kamereon/kca/car-adapter/v1/cars/{vin}/cockpit](https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/%7Baccount_id%7D/kamereon/kca/car-adapter/v1/cars/%7Bvin%7D/cockpit?country=DE)

B) The "My Dacia" app displays the TOTAL MILEAGE correctly.

C) The "My Dacia" app uses "car-adapter/v1/" instead of "car-adapter/v2/".

D) when I change line 29 in __init__.py like below I get valid data:
```diff
_KCA_GET_ENDPOINTS: Dict[str, Any] = {
    "": {"version": 2},
    "battery-status": {"version": 2},
    "charge-history": {"version": 1},
    "charge-mode": {"version": 1},
    "charges": {"version": 1},
    "charging-settings": {"version": 1},
+    "cockpit": {"version": 1},
-    ""cockpit": {"version": 2},
    "hvac-history": {"version": 1},
    "hvac-sessions": {"version": 1},
    "hvac-status": {"version": 1},
    "hvac-settings": {"version": 1},
    "location": {"version": 1},
    "lock-status": {"version": 1},
    "notification-settings": {"version": 1},
    "res-state": {"version": 1},
}
```

`DEBUG:renault_api.kamereon:Received Kamereon response 200 on GET to https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/XXXXXXXXXXX/kamereon/kca/car-adapter/v1/cars/XXXXXXXXXX/cockpit?country=DE: {"data":{"id":"UU1DBG005PU160283","attributes":{"totalMileage":667}}}`

**Comment by epenet** [comment]
Sadly, it seems that your endpoint doesn't work for all vehicles.

With v2, my Zoe is returning the same error "you should not be there but well done for the effort"
With v1, I get error 403: "Privacy mode currently ON"

`DEBUG:renault_api.kamereon:Received Kamereon response 403 on GET to https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/XXXXXXXXXXX/kamereon/kca/car-adapter/v1/cars/XXXXXXXXXX/res-state?country=FR: {"type":"FUNCTIONAL","messages":[{"code":"err.func.403","message":"{\"errors\":[{\"status\":\"403\",\"code\":\"security.access\",\"detail\":\"Access is denied for this resource\"}]}"}],"errors":[{"errorCode":"err.func.403","errorMessage":"{\"errors\":[{\"status\":\"403\",\"code\":\"security.access\",\"detail\":\"Access is denied for this resource\"}]}"}],"error_reference":"FUNCTIONAL"}`

**Comment by JapieG** [comment]
works for me, thanks!

**Comment by epenet** [comment]
> works for me, thanks!

Which vehicle?

**Comment by JapieG** [comment]
> > works for me, thanks!
> 
> Which vehicle?

Megane E-Tech

**Comment by epenet** [comment]
If it works for the Megane as well as for the Dacia, then I'm happy to take a PR

**Comment by ledermann** [comment]
I'm maintaining an API client implemented as a Ruby gem. Switching from `v2` to `v1` endpoint fixes the cockpit issue for me as well (using a Renault Zoe R135 Z.E. 50 from 2020). Thanks for this hint, @eltoro0815 👍

**Comment by eltoro0815** [comment]
I aborted the pull requests. Had no clue how to change it to only include one commit.

So that the pull request goes through quickly, someone experienced should probably do it.

**Comment by Konubinix** [comment]
@eltoro0815 If it is only a matter of submitting a PR with only this modification. I happily created it :-)

With my Dacia Spring, it also solved this issue.

**Comment by Konubinix** [comment]
Thank you @epenet for your reactivity on this issue

**Comment by anyvision** [comment]
Probably a VERY stupid question, but how do I get this fixed solution in my Home Assistent? I already removed it, and re-added it, but it remains the same?

**Comment by epenet** [comment]
Wait for 2024.4.4

**Comment by JapieG** [comment]
There are more changes now, bat temp no konger available on batterystatus request. Was always a non working static number, so no problem. But they are obviously doing things on the server side.

**Comment by oliv3r** [comment]
>  But they are obviously doing things on the server side.

Just leaving a note here, but it seems so indeed. The official app no longer shows 'time remaining' for example for me either, and I don't have access to the charging power anymore it seems. Looking at the raw endpoints a bit now to learn how this all works and what data we do/no longer have. Quite annoying. I mostly miss the 'charge power', as I find the time-estimate harder to read. Though with only that datapoint, we may end up having to estimate charging power; e.g. total battery capacity (- some offset due to battery aging) vs time ...
