### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connect call failed ('::', 443, 0, 0)

### ISSUE THREAD

**Issue by carygravel** [hacf-fr/renault-api#1255]
I'm getting the following traceback when trying the code in `API Usage` in the `README.md`. Obviously, I used my real credentials:
```
Traceback (most recent call last):
  File "/home/jeff/dev/renault-api/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1122, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1104, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1007, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 651, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 691, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('::', 443, 0, 0)
```

* Which operating system and Python version are you using?
Debian testing, python 3.12.4
* Which version of this project are you using?
0.2.4, installed via pip
* What did you do?
ran the code from `API Usage`
* What did you expect to see?
At least a list of available accounts
* What did you see instead?
The error message given above

**Comment by ddrrhh** [comment]
Since a couple of days calling the URL:
https://renault-wrd-prod-1-euw1-myrapp-one.s3-eu-west-1.amazonaws.com/configuration/android/config_de_DE.js

Leads to the error:
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>30ED3099BCEZFFN0</RequestId><HostId>D+jUIMTqXcCrfQtmGxOeQXDQt8Ol69i7uEa5+Z82AaB/ftJyVXfJ99fc+ttZXSDSIUaN3VDQse1OiT8eV0UJXg==</HostId></Error>

That may be connected with this issue.

**Comment by carygravel** [comment]
I'm still seeing problem with the latest version of `renault-api`. I can access the MyRenault app from my phone. I can ping `accounts.eu1.gigya.com`, but it doesn't open in a browser.

Do you have any tips on how to debug this further?

**Comment by ddrrhh** [comment]
Using curl in verbose mode for the request to
https://renault-wrd-prod-1-euw1-myrapp-one.s3-eu-west-1.amazonaws.com/configuration/android/config_de_DE.js

I get the answer:

 GET /configuration/android/config_de_DE.js HTTP/1.1
> Host: renault-wrd-prod-1-euw1-myrapp-one.s3-eu-west-1.amazonaws.com
> User-Agent: curl/8.8.0
> Accept: */*
>  Request completely sent off
< HTTP/1.1 403 Forbidden
< x-amz-request-id: 5N8HDCGJPVWKBP75
< x-amz-id-2: 75jDMc26qcnp2jhoQb/CmpY3RBfeH+WgZU3FaWbDyF+syecYtjBGiCFWVnUw5+sM/SIGuWfjG4o=
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Date: Sat, 27 Jul 2024 15:04:34 GMT
< Server: AmazonS3
....
It may be it needs autentification data here, or it doesn't accecpt "curl" as client

**Comment by carygravel** [comment]
I get exactly the same result. Does this mean that you can't use `renault-api` either, at the moment?
