### ISSUE TITLE
ZE50 AC cancel

### ISSUE THREAD

**Issue by PysX** [hacf-fr/renault-api#159]
AC Cancel seems not working with ZE 50.

Not really an issue as renault-api works, but it has no effect with the car.
```sh
renault-api hvac cancel
{'action': 'cancel'}
```

Starting is ok. 

May be this explain why in MyRenault App we can "Start" (then a timer of 5 min is display) but it is not possible to stop it.

May be this issue is more relative to HA component as the service has to be disabled in component a stay availaible in renault-api ?

**Comment by epenet** [comment]
@PysX do you have an error?
Or is it accepted but just doesn't have any effect?

If there is an error, we can fix.
If there is no error, then I think we should simply added to the documented on https://github.com/hacf-fr/renault-api/blob/main/docs/endpoints/vehicle_action.hvac-start.rst
Or maybe add a warning?

**Comment by PysX** [comment]
Correct : no errors and as no effect
I make a very small PR to update documentation.

To add a log warning, what is the best way ? Something like : 
```python
if '''model ZE50'''  #TODO
    _LOGGER.warning("Note : ac-cancel has no effect on ZE50.")
```
I don't know what is the best method to test model ZE50. It can be retrieved in `models`, but does `models` should be able to return if `ac-cancel` is available, like for endpoints ?

**Comment by epenet** [comment]
To check for a specific model, you can do `details = await self.get_details()` then check the model code property (X102VE is the Zoe 50)

We can't use `supports endpoint` as that is specific for errors and also the endpoint is shared between start and stop.  Maybe we add `warns on method xxx` that defaults to None? And is logged if not None?

**Comment by PysX** [comment]
Ok, thanks. Will try to do it this week.

**Comment by epenet** [comment]
Maybe something like this:

```
VEHICLE_SPECIFICATIONS: Dict[str, Dict[str, Any]] = {
    ......
    "X102VE": {  # ZOE phase 2
        "warns-on-method-set_ac_stop": "Action `cancel` on endpoint `hvac-start` may not be supported on this model.",
    },
    ......
}
```

**Comment by PysX** [comment]
Ok, this is what a tried. It works but should be "optimised".

- Message should be internaltionalized (yes/no?)
- May be we should make a function to avoid repeat all 3 lines to log in each method

Do you think i have to make a new PR or use the same about the documentation ?
What is your feedback ? Thanks !

models.py:
```python
    ...
    VEHICLE_SPECIFICATIONS: Dict[str, Dict[str, Any]] = {
        ......
        "X102VE": {  # ZOE phase 2
            "warns-on-method-set_ac_stop": "Action `cancel` on endpoint `hvac-start` may not be supported on this model.",
        },
        ......
    }
    ...

    def warns_on_method(self, method: str) -> str:
        """Return warning message if model trigger a warning on the method call."""
        # Default to None for unknown vehicles
        if self.model and self.model.code:
            return VEHICLE_SPECIFICATIONS.get(self.model.code, {}).get(
                f"warns-on-method-{method}", None
            )
        return None  # pragma: no cover
```
renault_vehicle.py
```python
 async def set_ac_stop(self) -> models.KamereonVehicleHvacStartActionData:
        """Stop vehicle ac."""
        attributes = {"action": "cancel"}
        details = await self.get_details()
        if details.warns_on_method('set_ac_stop') is not None:
            _LOGGER.warning(details.warns_on_method('set_ac_stop'))
...
```

**Comment by epenet** [comment]
I have merged #166, so you can create a new PR.

I suggest that you add a new method inside `renault_vehicle.py` that can be called at the start of each method endpoint.

```python
async def warn_on_method(self, method: str) -> None:
        """Log a warning if the method requires it."""
        details = await self.get_details()
        warning = details.warns_on_method(method)
        if warning:
            _LOGGER.warning(warning)
```

**Comment by PysX** [comment]
Thanks, I worked on it, it seems to work. (https://github.com/PysX/renault-api/tree/add-warning-on-method)
But now, tests are failing. As i understand it is because we call "details" in all methods now. I tried to fix by injecting fixture like the example below. Is this the best way ? 

```python
@pytest.mark.asyncio
async def test_set_ac_stop(
    vehicle: RenaultVehicle, mocked_responses: aioresponses
) -> None:
    """Test set_ac_stop."""
    url = fixtures.inject_set_hvac_start(mocked_responses, "cancel")
    fixtures.inject_get_vehicle_details(mocked_responses, "zoe_40.1.json")
    assert await vehicle.set_ac_stop()
....
```

**Comment by epenet** [comment]
I suggest for now you only implement `warn_on_method` for `set_ac_stop`, to avoid fixture injection on all the other methods.
We can add warn_on_method / fixture injection to the other methods as we add the corresponding warnings.

**Comment by PysX** [comment]
As you suggested, I have commented "unused" warning and then submit a PR !

**Comment by epenet** [comment]
@PysX I think we can close this now?

**Comment by PysX** [comment]
Yes !
