### ISSUE TITLE
SET Charge Mode in always from schedule_mode doesn't work

### ISSUE THREAD

**Issue by NathanRDN** [hacf-fr/renault-api#347]
Hello,

Just to inform, when you want to pass from schedule_mode to always mode, the CLI send a 400 error (see picture bellow). Is that normal ? I just looked speedly and I think it's coming from the Renault side. Have they changed the term or the format ?

![image](https://user-images.githubusercontent.com/68427027/128738603-292088ae-29fd-4a0e-9f0a-5bcf66d0663b.png)

**Comment by NathanRDN** [comment]
Ok I found !. It's not anymore "always". It's "always_charging" instead of always

**Comment by epenet** [comment]
Hi @NathanRDN,
What vehicle do you have?

In the past, it seemed that Zoe40 and Zoe50 were using a different code.
Maybe now Renault has standardised the process to always use "always_charging"?

**Comment by NathanRDN** [comment]
Hi @epenet. It was a Zoe 50, I will try on a Zoe 20 asap to be sure that it will work with the modif

**Comment by epenet** [comment]
Hi @NathanRDN,
Were you able to try both to confirm?
