### ISSUE TITLE
Lot of info available about endpoints, but not in readthedocs.io/

### ISSUE THREAD

**Issue by jumpjack** [hacf-fr/renault-api#380]
There are a lot of sample data available here:

https://github.com/hacf-fr/renault-api/tree/main/docs/endpoints

But only a few are reported in https://renault-api.readthedocs.io/en/stable/endpoints.html , and I don't understand if/how I can contribute just by writing online rather than by installing things on my PC.

Or is this the right page to edit?

https://github.com/hacf-fr/renault-api/wiki

It would be also useful to publish the endpoints which require parameters in url, visible for example [here](https://github.com/TA2k/ioBroker.renault/blob/de4ebbcd7053cefde0b0e785b25d39b53a52d8d0/main.js#L265), such as:

https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/ACCOUNTID/kamereon/kca/car-adapter/v1/cars/VIN/charge-history?**type=day&start=YYYY-MM-DD&end=YYYY-MM-DD**

https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/ACCOUNTID/kamereon/kca/car-adapter/v1/cars/VIN/charges?**start=YYYY-MM-DD&end=YYYY-MM-DD**

Also, publishing the templates of the payloads to be sent by POST requests would be useful for porting to other languages; they can be found [here](https://github.com/manu3b1/renault-api/tree/7c2336c52ed0298a3ed2b8e7dbb77b839676dced/tests/fixtures/kamereon/vehicle_action).

Finally, I found a lot of additional undocumented commands [here](https://github.com/mitchellrj/kamereon-python/blob/146904802301aa0b0008e2bdb3a88ed10ff50acf/kamereon/kamereon.py), who knows if they are supported by Renault too (it looks like they are for Nissan)

        actions/refresh-hvac-status
        actions/refresh-lock-status
        actions/refresh-location
        actions/srp-initiates
        actions/srp-sets
        actions/lock-unlock
        actions/horn-lights

        DataReset
        DeleteCurfewRestrictions
        CreateCurfewRestrictions
        CreateSpeedRestrictions
        SrpInitiates
        DeleteAreaRestrictions
        SrpDelete
        SrpSets
        OpenClose
        EngineStart
        LockUnlock
        CreateAreaRestrictions
        DeleteSpeedRestrictions

I prepared a page for testing new commands; it works also offline, so no need to send your credentials somewhere:

http://jumpjack.altervista.org/myrenault-debug/

**Comment by epenet** [comment]
https://github.com/hacf-fr/renault-api/tree/main/docs/endpoints
maps to
https://renault-api.readthedocs.io/en/latest/endpoints.html

**Comment by epenet** [comment]
For charge-history, you can use the source code from https://github.com/hacf-fr/renault-api/blob/109db4b3387a816a4c8fa7127962393abb0fd276/src/renault_api/renault_vehicle.py#L232-L235

And then you update https://github.com/hacf-fr/renault-api/blob/main/docs/endpoints/vehicle_data.charge-history.rst to add information about `type`, `start`, `end`

**Comment by epenet** [comment]
For the POST payloads, you can do it in the same way as the sample return (add a sample payload with the corresponding json file)

**Comment by epenet** [comment]
It seems you are still not willing to contribute to this project!
