### ISSUE TITLE
How to set "guid"?

### ISSUE THREAD

**Issue by jumpjack** [hacf-fr/renault-api#390]
What is "guid" here and in other fixtures, and to what should I set it to send a request?

https://github.com/hacf-fr/renault-api/blob/109db4b3387a816a4c8fa7127962393abb0fd276/tests/fixtures/kamereon/vehicle_action/hvac-schedule.schedules.json#L4

I would like to reset my schedule by an empty schedule payload.

**Comment by NathanRDN** [comment]
> This is data received from Renault servers so the GUID is generated by them not by us.

Hello,

How can I retreive this guid ? Is there a specific endpoint or something like that ?

**Comment by NathanRDN** [comment]
Oh yeah ? Because I thought that it must have been necessary to execute an action like launch a charge or stop it. I will test again this afternoon. Thanks for the quick answer by the way.

**Comment by jumpjack** [comment]
If I understand correctly, the id cam be used to follow execution status of "complex" (i.e which take some time to execute)  commands using "notifications" endpoint.

I am working on it, but I am not so good at "async javascript" so I am doing a mess... ;-)

Anyway, just to give you an idea about how to proceed:

This url shall be used to monitor command execution:

https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/persons/PERSONID/notifications/kmr?country=IT&notificationId=COMMAND_RESPONSE_ID

You should query it periodically to follow status evolution; some possible responses are  CREATED (as soon as command is received), PENDING while command is being processed,  COMPLETED (final result, if command successful), REJECTED.

I think Renault app replies with "Information sent  to the car" upon receiving "COMPLETED", but it does not further check if command is successful, because when I start the HVAC from the app I see this message "Information sent  to the car, you will receive notification", but I don't receive any notification, I shall manually check if HVAC is actually on.
 

```
function manageNotification(type) {
	//https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/persons/PERSONID/notifications/kmr?country=IT&notificationId=COMMAND_RESPONSE_GUID
	notificationUrl = kamereonurl + "/commerce/v1/persons/" +
	personId.value +
	"/notifications/kmr" +
	"?apikey=" + KAMEREON_KEY +
	"&country=" + country.value;
	if (type === "last") {
		notificationUrl +=	"&notificationId=" + notificationId;
	} else {
		// raw url provides info on all previous notifications
	}

	notificationHeaders = {
		'apikey': KAMEREON_KEY,
        'x-gigya-id_token' :  JWT.value
	};
    notifRetry = 0;
	CommandCompleted = false;
	notifInterval = setInterval(getNotificationStatus, NOTIF_INT);
}


function getNotificationStatus(mex) {
console.log(">>>>>>",mex,notifRetry);
	notifRetry++;
	axios.get(
		notificationUrl,
		{
			headers: notificationHeaders
		}
	)
	.then(response => {
		pippo = response;
		if (response.data.length === 0) { // In case of empty response, if command has not yet executed,  retry some times
			if (!CommandCompleted) {
				if (notifRetry >= NOTIF_MAX) { // Give up after a given number of attempts
					if (notifInterval) clearInterval(notifInterval);
					console.log(notifRetry, notifInterval, "Given up.");
					output.value += "\nGiven up.\n";
				} else {
					// retry
					console.log("Attempt n. " + notifRetry +  ", please wait...");
					output.value += "\nAttempt n. " + notifRetry + ", please wait...\n";
				}
			} else { // Empty because completed ==> exit
				if (notifInterval) clearInterval(notifInterval);
				CommandCompleted = true;
				console.log("Already finished, exiting.");
			}
		} else {
			//console.log("POST result for notification n. " + notificationId + ": " + (JSON.stringify(response.data, null, 4)));
			try {
				if (mex === "last") {
					console.log(response.data[response.data.length-1].notifDate + ": " + response.data[response.data.length-1].commandType + ", " +  response.data[response.data.length-1].commandResponse.status);
					output.value += "\n" + response.data[response.data.length-1].notifDate + ": " + response.data[response.data.length-1].commandType + ", " +  response.data[response.data.length-1].commandResponse.status;
				} else {
					for (i=0; i < response.data.length; i++) {
						console.log(response.data[i].notifDate + ": " + response.data[i].commandType + ", " +  response.data[i].commandResponse.status);
						output.value += "\n" + response.data[i].notifDate + ": " + response.data[i].commandType + ", " +  response.data[i].commandResponse.status;
					}
				}
				if (response.data[response.data.length-1].commandResponse.status == "COMPLETED") {
					if (notifInterval) clearInterval(notifInterval);
					CommandCompleted = true;
					console.log("PROCESSING COMPLETED.");
					output.value += "\nPROCESSING COMPLETED.";
				} else {
					//CommandCompleted = false;
					console.log("Waiting for command execution...");
					output.value += "\nWaiting for command execution..."
				}
			} catch (e) {
				console.log("data error, raw response for attempt " + notifRetry + ":", response, e);
				output.value += "Data error, see console for details";
			}
		}
	})
	.catch(
	  function (error) {
		log.value += "\nERROR 005 for POST while managing notification n. " + notificationId + ":\n" + error + "\n";
		console.log("ERROR 005 for POST while  managing notification n. " + notificationId + ":\n" + error);
		console.log("POST ERROR 005:" ,error)
	  	login1.innerHTML = "ERR_POST";
		return ({ status: "POST ERROR 005 (Notifications)", data: response.data });
		}
	);
}


```

**Comment by jumpjack** [comment]
By the way: apparently the only working method to stop a charge is to set a charge schedule; "CANCEL" and "STOP" do not work.

**Comment by jumpjack** [comment]
> You should query it periodically to follow status evolution; some possible responses are CREATED (as soon as command is received), PENDING while command is being processed, COMPLETED (final result, if command successful), REJECTED.

Found also "CANCELED" (=rejected, received upon trying to start HVAC when doors are unlocked) and "SYNCHRONIZED" (upon accepting Charging Start command).

So:

1. CREATED 
2. PENDING 
3. COMPLETED 
4. REJECTED
5. CANCELED
6. SYNCHRONIZED
