### ISSUE TITLE
Happy hacking and testing!

### ISSUE THREAD

**Issue by jumpjack** [hacf-fr/renault-api#391]
I am glad to announce my "test page" for developers and hackers which want to explore their cars capabilities:

http://jumpjack.altervista.org/myrenault/

Have fun and share your results! ;-)

Note: you don't need to put your credentials in the online version, the page works fine also if you save it locally.

**Comment by epenet** [comment]
This is just advertising/SPAM.
If you want to contribute => go ahead, discuss, create PR.
