### ISSUE TITLE
HVAC status

### ISSUE THREAD

**Issue by ZMan88** [hacf-fr/renault-api#439]
Hello,

I have found the when calling the following url https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/14573783-3ade-49c0-95ab-b65a130443c9/kamereon/kca/car-adapter/v1/cars/VF1AG000665929751/hvac-status?country=RO one can get the status of the ac. That would be useful to know when the ac (preconditioning) is running and see if you can trigger it again or not and also have a status for it.

the response from the call is: {"id":"blablabla","socThreshold":40.0,"lastUpdateTime":"2021-12-15T13:18:14Z","hvacStatus":"on"}

ca this be implemented as part of the repeated calls that are made to get the info? The preconditioning can also be triggerd

**Comment by epenet** [comment]
What vehicle do you have?
`hvac-status` was known to have bugs on some vehicles - but maybe those are fixed now.

You can also see this documentation: https://renault-api.readthedocs.io/en/latest/usage.html#renault-api-hvac and https://renault-api.readthedocs.io/en/latest/reference/renault_api.html#renault_api.renault_vehicle.RenaultVehicle.get_hvac_status

If you feel there is functionnality missing, don't hesitate to provide a pull request.

**Comment by epenet** [comment]
I think we can close this since https://github.com/hacf-fr/renault-api/pull/452 was merged?
