### ISSUE TITLE
Renault Trafic III (2021)

### ISSUE THREAD

**Issue by auveele** [hacf-fr/renault-api#471]
Hi,

I've recently bought a Renault Trafic III with EasyLink.
`code='X822VP', label='TRAFIC III'`

I was playing with this API, and there are some features that don't work with my van. I understand that it is obvious, like the charge info, because my van works with Diesel.

I would like to be able to collaborate with the project, and if it is necessary to test some functions. I have some Python experience ;)

Thanks in advance!

**Comment by epenet** [comment]
Help is always welcome.
I suggest that you start by providing some new fixture files: see https://github.com/hacf-fr/renault-api/issues/48

**Comment by epenet** [comment]
Hi, did you have a chance to collect some fixture files?
