### ISSUE TITLE
Systematic "403 Forbidden" on any API calls

### ISSUE THREAD

**Issue by dlecan** [hacf-fr/renault-api#555]
Hello,

I have been using this great project for weeks without any lasting errors 😅
But for 2 days, it is now impossible to call any Renault API without an error.
I always get `403 Forbidden`: `status`, `accounts` ...

`login` command works perfectly

Any clue? Something updated on Renault API which must be reflected in this project?

I'm using version last version 0.1.9 of this project

Thank you

**Comment by epenet** [comment]
See  #552
New release is already available

**Comment by dlecan** [comment]
Arf, so quick response and release 👏
I didn't check this morning 

It's working again

Thank you
