### ISSUE TITLE
CircuitBreaker error

### ISSUE THREAD

**Issue by gletellier** [hacf-fr/renault-api#624]
I have been using this api successfully since few week with Dacia Spring. It suddenly cease to function yesterday at 3am Cest.

I receive following error message when running renault-api status

`battery-status: CircuitBreaker 'vehiclesCircuitBreaker' is OPEN and does not permit further calls
charge-mode: CircuitBreaker 'vehiclesCircuitBreaker' is OPEN and does not permit further calls
cockpit: CircuitBreaker 'vehiclesCircuitBreaker' is OPEN and does not permit further calls
location: CircuitBreaker 'vehiclesCircuitBreaker' is OPEN and does not permit further calls
lock status: CircuitBreaker 'vehiclesCircuitBreaker' is OPEN and does not permit further calls
res state: CircuitBreaker 'vehicles Circuit Breaker is OPEN and does not permit further calls`

Here an excerpt of same command with debug option. 

`DEBUG:renault_api.kamereon:Received Kamereon response 500 on GET to https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/1cd7e385-XXXX-XXXX-9b03-a287074e7ef2/vehicles/xxxxxxxxxxxx/details?country=FR: {"type":"TECHNICAL","messages":[{"code":"err.tech.wired.vehicle-details","message":"CircuitBreaker 'vehiclesCircuitBreaker' is OPEN and does not permit further calls"}]`

**Comment by epenet** [comment]
This is an issue on the Renault side, not an issue with this tool.
I expect that the phone app has also stopped working for you, and I suggest that you contact Renault through their support desk.

**Comment by gletellier** [comment]
Your are right, it must have be on Renault side as it resolved itself spontaneously this morning.

By the way, the application was working fine while the api client wasn't.
