### ISSUE TITLE
502 Server Error: Bad Gateway

### ISSUE THREAD

**Issue by epenet** [hacf-fr/renault-api#72]
Originally opened by @WinkelB on [hassRenaultZE](https://github.com/hacf-fr/hassRenaultZE/issues/51)

```
Logger: custom_components.renault.pyzevehicleproxy
Source: helpers/update_coordinator.py:152
Integration: Renault (documentation)
First occurred: 21:55:16 (1 occurrences)
Last logged: 21:55:16

Error requesting VINXXXXXXXXXXXX hvac_status data: 502 Server Error: Bad Gateway for url: https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/ACCOUNTXXXXXXXXXXXXXXX/kamereon/kca/car-adapter/v1/cars/VINXXXXXXXXXXXX/hvac-status?country=DE
```

**Comment by epenet** [comment]
I have the same issue here with charge-mode:

```
Received Kamereon response 500 on https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/ACCOUNTXXXXXXXXXXXXXXX/kamereon/kca/car-adapter/v1/cars/VINXXXXXXXXXXXX/charge-mode?country=FR:
{"type":"TECHNICAL","messages":[{"code":"err.tech.500","message":"{\"errors\":[{\"status\":\"Internal Server Error\",\"code\":\"500\",\"title\":\"Invalid response from the upstream server (The request sent to the GDC is erroneous) ; 502 Bad Gateway\"}]}"}],"errors":[{"errorCode":"err.tech.500","errorMessage":"{\"errors\":[{\"status\":\"Internal Server Error\",\"code\":\"500\",\"title\":\"Invalid response from the upstream server (The request sent to the GDC is erroneous) ; 502 Bad Gateway\"}]}"}],"error_reference":"TECHNICAL"}
```

I have contacted Renault about it, as it prevent me from planning the charges inside MyRenault application.

**Comment by epenet** [comment]
@WinkelB: I have contacted Renault and they solved something at their end.
Now my charge management works fine.

Did you manage to get it working on your end?

**Comment by WinkelB** [comment]
I'm not getting these error message anymore.
But now there is an operation not supported error message

Error fetching VF1XXX hvac_status data: This endpoint has been disabled:
('err.func.403', 'Operation not supported Operation not supported for this
can (C1A)')

epenet <notifications@github.com> schrieb am Do., 17. Dez. 2020, 08:09:

**Comment by epenet** [comment]
Do you have air conditioning in your vehicle?
Are you able to control it via the MyRenault application?

**Comment by WinkelB** [comment]
Yeah I'm also able to start the heating for example via the services from
homeassistant

epenet <notifications@github.com> schrieb am Do., 17. Dez. 2020, 09:05:

**Comment by epenet** [comment]
The joys of Renault AIP...
On ZE40, it always returns "off" even when it's on. Maybe on ZE50 they simply disabled the endpoint.
On Home-Assistant, it will just display the error once at startup, and then disable the endpoint.

Are you happy to close this?

**Comment by PysX** [comment]
I can confirm for my ZE50: the hvac-status endpoint is not supported.
However I am able to start AC from MyRenault App and from API.
In Renault App, it is like it starts a timer for 5min, can not stop it.
Not tested “stop” from API.

**Comment by epenet** [comment]
Documentation added to wiki: https://github.com/hacf-fr/renault-api/wiki/Data-endpoint:-hvac-status

I will close it, and we can discuss on hassRenaultZE what is the best way to handle it there.
