### ISSUE TITLE
Renault API not working - ClientResponseError: 403, message='Forbidden' 

### ISSUE THREAD

**Issue by mathieucarbou** [hacf-fr/renault-api#847]
Please see https://github.com/home-assistant/core/issues/91593#issuecomment-1512733779

> It looks like a change on the Renault servers - not linked to `2023.4.5`
> We might need a new API key, similar to https://github.com/hacf-fr/renault-api/pull/552
> Please open an issue on renault-api repository.

_Originally posted by @epenet in https://github.com/home-assistant/core/issues/91593#issuecomment-1512733779_

**Comment by epenet** [comment]
Fixed via #848
