### ISSUE TITLE
Adding to HA - Unknown Error Occurred 

### ISSUE THREAD

**Issue by IAlves2022** [hacf-fr/renault-api#852]
Hy guys, i'm using this api for a time, and from a few days it stop working,,, I've thought that it was better to remove a install it again.

After remove, I'm trying to add it again in HA, and on the credentials screen when I try to log in it gives me this error.

How can i solve this please?!

![WhatsApp Image 2023-04-20 at 00 45 25](https://user-images.githubusercontent.com/97402038/233222865-2fefc1b0-a899-42c4-8900-229db81561a5.jpeg)

**Comment by epenet** [comment]
See https://github.com/home-assistant/core/issues/91593
