### ISSUE TITLE
Quota limit reached, then vnext error 401

### ISSUE THREAD

**Issue by PaulMuadDib** [hacf-fr/renault-api#857]
This occured 48h after the renault api key change. Any idea ? 
![image](https://user-images.githubusercontent.com/4218461/233838258-9a446e16-94c9-4e12-8b9a-8568a2b911fb.png)

**Comment by dbwarrior1975** [comment]
Maybe not related to same root cause, but for me same command is giving this kind of errors: 
![kuva](https://user-images.githubusercontent.com/80710485/233847801-e2d1bf8d-5cfd-4bb0-b6e3-70ac546be465.png)

**Comment by Smartdatalog** [comment]
Same effect some days after the last API key change. The API call stopped on the 23/04/2023 19h24  (UTC+2)
Error : 404 Not Found: Requested route ('alliance-platform-caradapter-prod.apps.eu.kamereon.io') does not exist.
Now, DACIA android mobile app isn't giving any mileage and other parameters. May be some trouble with the server ???

**Comment by Smartdatalog** [comment]
From my side, it was due to a renault server problem. Everything went up without anny intervention on the 23/04/2023 20:48 GMT+2

**Comment by dbwarrior1975** [comment]
Yes, it was few hours black out.
