### ISSUE TITLE
Certificate validation error in cli

### ISSUE THREAD

**Issue by kreuzhofer** [hacf-fr/renault-api#901]
Probably an issue on Renault side but the certificate cannot be validated at the moment:

aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host accounts.eu1.gigya.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')]

When using the sample code, this can be fixed by ignoring cert validation errors, which is not ideal but it also has to be done for the cli unless Renault fixes their cert chain.

async with aiohttp.ClientSession(connector=aiohttp.TCPConnector(verify_ssl=False)) as websession:

**Comment by epenet** [comment]
Gigya is not just for Renault.
We know Renault often has issues but Gigya less so.

I wouldn't want to implement this as default.
