### ISSUE TITLE
Charging Remaining Time has value when the battery is not being charged.

### ISSUE THREAD

**Issue by MilorES** [hacf-fr/renault-api#920]
I use Home Assistant which I understand is based on this API.

![imagen](https://github.com/hacf-fr/renault-api/assets/7502697/e1eaa683-78bc-4055-90b6-e380a7e8fbff)

It should be at 0, right? How to send the time format? Can it only be done in seconds?

**Comment by epenet** [comment]
If you enable debug mode you will see the raw data coming from Renault servers.

**Comment by MilorES** [comment]
Can I do that with the integration in Home Assistant? (I do not see it)
Which enables? If it always arrives in minutes... I can multiply it * 60

Note: What surprises me is that the API sends you a remaining time when it is no longer loading... I'll have to modify it by hand.

**Comment by epenet** [comment]
Yes you can enable debug inside home assistant. 
Either in yaml, or in the integration settings.
