### ISSUE TITLE
Installation on macOS

### ISSUE THREAD

**Issue by ik2wxx** [hacf-fr/renault-api#95]
For anyone interested in installing the script in macOS, I had to:

install renault-api with this command
`$ sudo -H python3 -m pip install renault-api`

install click
`$ sudo -H python3 -m pip install click`

install tabulate
`$ sudo -H python3 -m pip install tabulate`

add this path to PATH variable in .zprofile file
`/Users/YOUR_USER_NAME_HERE/Library/Python/3.8/bin`

install python.dateutil
`$ sudo -H python3 -m pip install python.dateutil`

*create a "logs" folder in user root folder

**Comment by epenet** [comment]
You can install the click/tabulate and other CLI dependencies with this command: `pip install renault-api[cli]`

Do you want to create a PR?

**Comment by ik2wxx** [comment]
> Do you want to create a PR?
If someone can please make a fix for new macOS users, or can add infos in the installation instructions (https://github.com/hacf-fr/renault-api/#installation), it's ok.

**Comment by epenet** [comment]
Hi @ik2wxx

I have merged #100 which will auto-create the logs folder, and I am working on #71 to update the documentation.
Can you please confirm what command you are using at the end to run the renault-api?

Are you using this? Or something different?
```console
   $ sudo -H python3 -m renault-api --log status
```

**Comment by ik2wxx** [comment]
> I have merged #100 which will auto-create the logs folder, and I am working on #71 to update the documentation.
> Can you please confirm what command you are using at the end to run the renault-api?
> Are you using this? Or something different?
>    $ sudo -H python3 -m renault-api --log status

I just type
"renault-api status"
no need to call python3

Thank you

**Comment by epenet** [comment]
@ik2wxx I have now merged #100 and #71.

In my opinion, the remaining items `sudo -H python3 -m` and `PATH variable in .zprofile file` do not really belong in the documentation but if you find a suitable place and wish to make a documentation PR I will consider it.

If not, then I think we can close this issue.

**Comment by ik2wxx** [comment]
That's ok for me. Thank you.
