### ISSUE TITLE
HVAC status output processed wrong on Captur

### ISSUE THREAD

**Issue by HomeACcessoryKid** [hacf-fr/renault-api#986]
Using this wonderful project, I discovered this anomaly on a Captur:

`KamereonVehicleHvacStatusData(raw_data={'socThreshold': 20.0, 'hvacStatus': 'off', 'internalTemperature': 21.0, 'lastUpdateTime': '2023-09-23T14:41:08Z'}, lastUpdateTime='2023-09-23T14:41:08Z', externalTemperature=None, hvacStatus='off', nextHvacStartDate=None, socThreshold=20.0)`

I observe that the raw_data contains different items than the parsed data.

If you confirm this is not as intended - maybe this is just a difference between models of cars - then I can work on a PR.
Please DO give some guidance what would be the intention.

**Comment by epenet** [comment]
Renault API is fully undocumented, and the features for different cars vary.
In this particular case, I suggest that you add a PR to add the missing fields (don't remove the absent fields as they are present on other cars) together with a "real" fixture file and adjusted tests.

**Comment by HomeACcessoryKid** [comment]
Thanks for the advice. I'll have a go at it some time in the future.

**Comment by HomeACcessoryKid** [comment]
Not likely, sorry about that...
